### ISSUE TITLE
TASK initial stateless backend service

### ISSUE THREAD

**Issue by thejhh** [hangovergames/project-memory#22]
### Goal

Stateless backend for the memory matching game. It will utilize cryptography to pass the game state back to the frontend. It will not have any kind of authentication or state.

This will be private source code, Github repository at [hangovergames/memory](https://github.com/hangovergames/memory/issues/21).

### Subtasks

* [x] Implement a game request dto
* [x] Implement a game state dto
* [x] Implement a game state encryption and decryption
* [x] Implement a new game starting and card visibility
* [x] Implement a step in the game to match cards
* [x] Implement creation and update times
* [x] Document the API in the README
* [x] Manual test it
