### ISSUE TITLE
TASK Implement game server on public network

### ISSUE THREAD

**Issue by thejhh** [hangovergames/project-memory#28]
### Goal

Implement game server on public network so that the frontend can be tested without backend source code

### Subtasks

* [x] Add scripts for cross platform releases
* [ ] Enable static build
* [ ] Build cross platform releases
* [ ] Install as a systemd service 
* [ ] Test https://memory.hangover.games
