### ISSUE TITLE
TASK Add unit tests for gamestate

### ISSUE THREAD

**Issue by thejhh** [hangovergames/project-memory#32]
### Goal

Write unit tests to improve the game

### Subtasks

* [x] gamestate.go coverage 97,1%, remaining not important cases
  * [x] Write tests for `NewGameState`
  * [x] Write tests for `ToggleCard`
  * [x] Write tests for `UpdateScore`
